# Generated by Django 4.0.3 on 2022-04-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='positions',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='value',
            new_name='price_value',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='value',
            new_name='price_value',
        ),
        migrations.CreateModel(
            name='PlayerMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_history', to='team.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_history', to='team.team')),
            ],
        ),
    ]
