# Generated by Django 4.0.3 on 2022-04-10 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_positions_player_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='player',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermarket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='playermarket',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='team',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified on'),
            preserve_default=False,
        ),
    ]
