# Generated by Django 4.0.3 on 2022-04-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_created_on_player_modified_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='playermarket',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('pk',)},
        ),
    ]
