# Generated by Django 4.0.3 on 2022-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_player_options_alter_playermarket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermarket',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
