# Generated by Django 4.0.3 on 2022-04-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
